version: "3.8"
services:
  client:
    image: webapp-client
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - api
    networks:
      - webappnetwork

  api:
    image: webapp-api
    build: ./server
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - mongodb
    networks:
      - webappnetwork

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    command: mongod --noauth --smallfiles
    networks:
      - webappnetwork

networks:
  webappnetwork: # networks must be a dictionary
    driver: bridge

volumes:
  mongo-data:
    driver: local
